### ISSUE TITLE
Only the first item in packages exclude is blacklisted

### ISSUE THREAD

**Issue by emilyzheng** [release-engineering/ubi-population-tool#33]
When UBI configuration has:
```
packages:
  include:
  - MySQL-python.*
  - ethtool.*
  exclude:
  - ethtool*
  - MySQL-python*
```
Log of ubipop dry-run has:
```
2019-04-01 07:19:27 +0000 [INFO    ] Would associate MySQL-python-1.2.5-1.el7.x86_64.rpm from rhel-7-server-rpms__7Server__x86_64 to ubi-7-server-rpms__7Server__x86_64
```
MySQL-python is not excluded because package_list in the second loop of self._parse_blacklist_config() is empty when package_list is itertools.chain object.
```
    def get_blacklisted_packages(self, package_list):
        """
        Finds blacklisted packages in output sets
        """
        blacklisted_pkgs = []
        for pattern_name, globbing, pattern_arch in self._parse_blacklist_config():
            for package in package_list:
```
