### ISSUE TITLE
[regression] Blacklist package is published

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-population-tool#60]
Blacklisted package from include is published even if in the blacklist.

```yaml
packages:
  include:
  - MySQL-python.*
  - MySQL-python-debuginfo.*
  blacklist:
  - MySQL-python-debuginfo
```

or

```yaml
packages:
  include:
  - MySQL-python.*
  - MySQL-python-debuginfo.*
  blacklist:
  - MySQL-python-debuginfo.*
```
